services:
  rabbitmq-node1:
    image: rabbitmq-with-cookie:latest
    container_name: rabbitmq-node1
    hostname: hw05-rmq-node1
    restart: always
    volumes:
      - rabbitmq-node1-data:/var/lib/rabbitmq/
      - rabbitmq-node1-logs:/var/log/rabbitmq/
    command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
    networks:
      - rmq-cluster-network

  rabbitmq-node2:
    image: rabbitmq-with-cookie:latest
    container_name: rabbitmq-node2
    hostname: hw05-rmq-node2
    restart: always
    volumes:
      - rabbitmq-node2-data:/var/lib/rabbitmq/
      - rabbitmq-node2-logs:/var/log/rabbitmq
    command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
    networks:
      - rmq-cluster-network

  rabbitmq-node3:
    image: rabbitmq-with-cookie:latest
    container_name: rabbitmq-node3
    hostname: hw05-rmq-node3
    restart: always
    volumes:
      - rabbitmq-node3-data:/var/lib/rabbitmq/
      - rabbitmq-node3-logs:/var/log/rabbitmq
    command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
    networks:
      - rmq-cluster-network

  haproxy:
    image: haproxy:latest
    container_name: haproxy-load-balancer
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq-node1
      - rabbitmq-node2
      - rabbitmq-node3
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rmq-cluster-network

networks:
    rmq-cluster-network:
      driver: bridge
      external: true


volumes:
  rabbitmq-node1-data:
  rabbitmq-node1-logs:
  rabbitmq-node2-data:
  rabbitmq-node2-logs:
  rabbitmq-node3-data:
  rabbitmq-node3-logs:
