server:
  port: 8080
spring:
  application:
    name: RabbitMqProducerApp
  messages:
    encoding: utf-8
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
  profiles:
    active: dev
  rabbitmq:
    addresses: ${RABBIT_ADDRESSES:"localhost"}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: ${RABBIT_VIRTUAL_HOST:/}
    publisher-confirm-type: simple
logging:
  level:
    root: error
    ru.otus.rabbitmq.hw.requestor.service: info